import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./_components/Sidebar";
import AltSidebar from "./_components/AltSidebar";
import Noise from "./_components/Noise";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false; /* eslint-disable import/first */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getScript({
  mode,
  defaultMode,
  localStorageKey,
}: {
  mode?: string;
  defaultMode: string;
  localStorageKey: string;
}) {
  return `
    try {
      const mode = window.localStorage.getItem('${localStorageKey}') ?? '${mode}' ?? '${defaultMode}';
      const computedMode =
        mode === 'auto' ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : mode;

      if (computedMode === 'dark') {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
    } catch (e) {}
  `;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          data-flowbite-theme-mode-script
          dangerouslySetInnerHTML={{
            __html: getScript({
              mode: "light",
              defaultMode: "light",
              localStorageKey: "theme",
            }),
          }}
        />
      </head>
      <body className="dark:bg-stone-900 bg-stone-200">
        {/* <Noise /> */}
        <div className="transition-colors flex flex-row h-screen w-screen font-diatype text-stone-600 dark:text-stone-200 text-sm">
          <Sidebar />
          <main className="w-5/12 py-10 mx-auto">
            {children}
          </main>
          <AltSidebar />
        </div>
      </body>
    </html>
  );
}
