import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./_components/Sidebar";
import AltSidebar from "./_components/AltSidebar";
import Noise from "./_components/Noise";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false; /* eslint-disable import/first */

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Noise /> */}
        <div className="transition-colors flex flex-row h-screen w-screen bg-stone-200 dark:bg-stone-900 font-diatype text-stone-600 dark:text-stone-200 text-sm">
          <Sidebar />
          <div className="w-5/12 py-10 mx-auto">
            {children}
          </div>
          <AltSidebar />
        </div>
      </body>
    </html>
  );
}
